- platform: mqtt
  name: gas boiler
  icon: mdi:radiator
  # state_topic: "/heater1/relay/state"
  state_topic: "/gasboiler/gpio/12"
  command_topic: "/gasboiler/gpio/12"
  payload_on: "1"
  payload_off: "0"
  retain: true
