- platform: mqtt
  name: waterpump
  icon: mdi:water-pump
  # state_topic: "/waterpump/relay/state"
  state_topic: "/waterpump/gpio/12"
  command_topic: "/waterpump/gpio/12"
  payload_on: "1"
  payload_off: "0"
  retain: true
