
- id: '1538633801540'
  alias: morning on
  initial_state: 'off'
  trigger:
  - at: '6:15:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.sonoff
    service: switch.turn_on

- id: '1538633891700'
  alias: morning off
  initial_state: 'off'
  trigger:
  - at: '7:05:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.sonoff
    service: switch.turn_off

- alias: water leave home
  trigger:
    platform: state
    entity_id: device_tracker.iphone6
    to: not_home
  action:
  - service: switch.turn_off
    entity_id: switch.waterpump

- alias: water at home
  trigger:
    platform: state
    entity_id: device_tracker.iphone6
    to: home
  action:
  - service: switch.turn_on
    entity_id: switch.waterpump

- alias: Heater Auto On for 60 Minutes Every 2 Hour From 11pm to 7am
  # id: FT Bed Heater Auto On for 30 Minutes Every 2 Hour From 11pm to 6am
  trigger: 
    platform: time
    minutes: '/120'
    seconds: 0
  condition:
  - condition: time
    after: '21:00:00'
    before: '07:00:00'
  action:
  - entity_id: switch.heater1
    service: switch.turn_on
  - delay: '00:60:00'
  # - delay: '00:{{ states.input_number.rosikroomtimer.state | int }}:00'
  - entity_id: switch.heater1
    service: switch.turn_off

# - alias: FT Bed Heater Auto On for 30 Minutes Every 2 Hour From 11pm to 6am
#   id: FT Bed Heater Auto On for 30 Minutes Every 2 Hour From 11pm to 6am
#   trigger: 
#     platform: time
#     hour: '/2'
#     minutes: 0
#     seconds: 0
#   condition:
#   - condition: time
#     after: '23:00:00'
#     before: '07:00:00'
#   action:
#   - entity_id: switch.ftheater
#     service: homeassistant.turn_on
#   - delay: 00:30:00
#   - entity_id: switch.ftheater
#     service: homeassistant.turn_off