homeassistant:
  # Name of the location where Home Assistant is running
  name: Awesome home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 300
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Kiev
  # Customization file
  # customize: !include_dir_merge_named customize
  packages: !include_dir_named packages/
  whitelist_external_dirs:
    - '/home/homeassistant/.homeassistant/pic'
#    - /home/pi/Pictures

zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 75
    icon: mdi:home-automation

  - name: Ol4uk Work    
    latitude: !secret wolatitude
    longitude: !secret wolongitude
    radius: 150
    icon: mdi:office-building

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
    themes: !include themes.yaml

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  api_password: !secret apipass 
  ssl_certificate: !secret sslcert
  ssl_key: !secret sslkey
  base_url: !secret domainname
  ip_ban_enabled: true
  login_attempts_threshold: 5

# api:

duckdns:
  domain: !secret domainname
  access_token: !secret duckdnstoken


updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

recorder:
  # purge_keep_days: 10

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# mqtt broker
mqtt:
  broker: 192.168.1.170
  port: 1883
  #client_id: homeassistant-1
  username: !secret mqttuser
  password: !secret mqttpass
  # password: !secret mqttpass
  discovery: true
  discovery_prefix: homeassistant

vacuum:
  - platform: xiaomi_miio
    discovery_retry: 5
    host: 192.168.1.35
    token: !secret xiaomi_vacuum_token

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: !secret mi_gateway_mac
      key: !secret mi_gateway_key

device_tracker:
  - platform: bluetooth_tracker
    interval_seconds: 120
    new_device_defaults:
      track_new_devices: false

#  - platform: ping
#    interval_seconds: 60
#    consider_home: 1200
#    hosts:
#      serj_phone: 192.168.1.134

  - platform: icloud
    username: !secret icloudusername
    password: !secret icloudpasswd
    account_name: Ol4uk
    max_interval: 20
    track_new_devices: true

  - platform: google_maps
    username: !secret googlemapsusername 
    password: !secret googlemapspassword 

person:
  - name: Ol4uk
    id: ol4uk18
    device_trackers:
      - device_tracker.iphone6
      - device_tracker.iphone6_bt

  - name: Serj
    id: Serj88
    device_trackers:
      - device_tracker.nexus_6p_bt
      - device_tracker.google_maps_118095117966834362307


binary_sensor: 
  - platform: command_line
    name: Mosquitto 
    command: sudo systemctl status mosquitto.service | awk 'FNR==3 { print $3 }' 
    device_class: connectivity
    payload_on: "(running)"
    payload_off: "(dead)"

telegram_bot:
  - platform: polling
    api_key: !secret tg_api_key
    allowed_chat_ids:
      - !secret tg_chat_id
 
notify:
  - name: NOTIFIER_NAME
    platform: telegram
    chat_id: !secret tg_chat_id

logger:
  default: fatal 

google_assistant:
  project_id: !secret goole_project_id 
  api_key: !secret google_api_key 
  exposed_domains:
    - switch
    - light
    - climate
    - script
#lovelace:
#  mode: yaml

media_player:
  - platform: xiaomi_miio_gateway
    host: 192.168.1.105
    token: !secret mi_gateway_token

system_health:

shopping_list:

fastdotcom: 

# speedtestdotnet:

# light:
#   - platform: switch
#     name: bedroom light
#     entity_id: switch.sonoff

# group: !include groups.yaml

# automation: !include_dir_merge_list automation/
# automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors/
shell_command: !include shell/shell_commands.yaml

