title: My Awesome Home
background: center / cover no-repeat url("/background.png") fixed
views:
######################  
  - title: Home
    id: home
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:  
    - type: picture-elements
      image: /local/welcome-home.png
      elements:
      - type: icon
        icon: mdi:home-outline
        entity: climate.home_gas_heater
        tap_action: more-info
        style:
          top: 82%
          left: 15%              
          color: white
      - type: state-label
        entity: sensor.temperature_158d00023cf7f5
        style:
          top: 95%
          left: 15%
          color: white
      - type: icon
        icon: mdi:baby-buggy
        entity: climate.rosik_ceramik_heater
        tap_action: more-info
        style:
          top: 82%
          left: 85%              
          color: white
      - type: state-label
        entity: sensor.temperature_158d00024781ee
        style:
          top: 95%
          left: 85%
          color: white
    - type: entities
      title: Газовий котел
      show_header_toggle: false
      entities:
        - entity: climate.home_gas_heater
          name: клімат-контроль
        - entity: switch.gas_boiler
          name: газовий котел
          secondary_info: last-changed
    - type: entities
      title: Дитяча
      show_header_toggle: false
      entities:
        - entity: climate.rosik_ceramik_heater
          name: клімат-контроль
        - entity: switch.heater1
          secondary_info: last-changed
          name: керамічна панель
        - entity: sensor.heater_on
          name: годин роботи обігрівача
    - type: history-graph
      title: Температура та Вологість
      entities:
        - entity: sensor.temperature_158d00023cf7f5
          name: кухня
        - entity: sensor.temperature_158d00024781ee
          name: дитяча
        - entity: sensor.dark_sky_temperature 
          name: за бортом
    # - type: history-graph
    #   title: Вологість
    #   entities:
        - entity: sensor.humidity_158d00024781ee
          name: дитяча
        - entity: sensor.humidity_158d00023cf7f5
          name: кухня
    - type: entities
      title: Вода
      show_header_toggle: false
      entities: 
        - entity: switch.waterpump
          name: насос
          secondary_info: last-changed
        - entity: sensor.water_pump_on
          name: годин активності
        - entity: binary_sensor.water_leak_sensor_158d00023a7ccf
          name: датчик протікання
          secondary_info: last-changed
        - entity: automation.water_at_home
          name: Вкл воду коли ми вдома
        - entity: automation.water_leave_home
          name: Викл воду коли нікого вдома
    - type: entities
      title: Спальня
      show_header_toggle: false
      entities:
        - entity: light.gateway_light_7c49eb1a6912
          name: нічник
        - entity: sensor.illumination_7c49eb1a6912
          name: освітленність
        - entity: switch.sonoff
          name: лампа

    # - type: picture-elements
    #   image: /local/vacuum_cleaner.png
    #   elements:
    #   - type: icon
    #     icon: mdi:bell-ring
    #     tap_action: call-service
    #     entity: vacuum.xiaomi_vacuum_cleaner
    #     service: vacuum.locate
    #     style:
    #       top: 80%
    #       left: 80%
    #       "--paper-item-icon-color": rgb(115, 122, 130)
    #   - type: icon
    #     tap_action: call-service
    #     icon: mdi:home
    #     entity: vacuum.xiaomi_vacuum_cleaner
    #     service: vacuum.return_to_base
    #     style:
    #       top: 80%
    #       left: 60%
    #       "--paper-item-icon-color": rgb(115, 122, 130)
    #   - type: icon
    #     icon: mdi:play-pause
    #     tap_action: call-service
    #     entity: vacuum.xiaomi_vacuum_cleaner
    #     service: vacuum.start_pause
    #     style:
    #       top: 80%
    #       left: 40%
    #       "--paper-item-icon-color": rgb(115, 122, 130)
    #   - type: icon
    #     icon: mdi:stop
    #     tap_action: call-service
    #     entity: vacuum.xiaomi_vacuum_cleaner
    #     service: vacuum.stop
    #     style:
    #       top: 80%
    #       left: 20%
    #       "--paper-item-icon-color": rgb(115, 122, 130)
    #   - type: state-label
    #     entity: sensor.vacuum_status
    #     style:
    #       top: 10%
    #       left: 5%
    #       color: rgb(255, 255, 255)
    #       transform: translate(0%,-50%)
    #       pointer-events: none
    #       text-shadow: 1px 1px black
    #       font-family: Trebuchet MS
    #       font-size: 90%
    #       font-weight: bold
    #       border-left-style: solid
    #       border-color: rgb(34, 154, 210)
    #       background-color: rgb(54, 65, 78)
    #       opacity: 0.8
    #   - type: state-label
    #     entity: sensor.vacuum_battery
    #     style:
    #       top: 10%
    #       right: 5%
    #       color: rgb(255, 255, 255)
    #       transform: translate(0%,-50%)
    #       pointer-events: none
    #       text-shadow: 1px 1px black
    #       font-family: Trebuchet MS
    #       font-size: 90%
    #       font-weight: bold
    #       border-right-style: solid
    #       border-color: rgb(34, 154, 210)
    #       background-color: rgb(54, 65, 78)
    #       opacity: 0.8
    # # - type: markdown  
    #   title: Lovelace
    #   content: >
    #     Welcome to your **Awesome home**.
#################  
  - icon: mdi:information-outline
    id: info
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - type: weather-forecast
        entity: weather.dark_sky
      - type: history-graph
        title: Тиск
        entities:
          - entity: sensor.pressure_158d00024781ee
            name: дитяча
          - entity: sensor.pressure_158d00023cf7f5
            name: кухня
      - type: entities
        entities:
          - entity: device_tracker.iphone6
            secondary_info: last-changed
          - entity: device_tracker.nexus_6p_bt
            secondary_info: last-changed
#      - type: map
#        aspect_ratio: 100%
#        entities:
#         - entity: device_tracker.iphone6
#         - entity: device_tracker.iphone6_bt
#         - entity: device_tracker.nexus_6p_bt 
#         - zone.home
#         - zone.ol4uk_work
####################
  - icon: mdi:palette-swatch
    title: Сущности
    background: radial-gradient(crimson, skyblue)
    cards:
      - type: entities
        title: Система
        entities:
          - sensor.ssl_cert_expiry
          - sensor.external_ip
          - sensor.ha_last_version
      - type: entities
        title: Все бинарные сенсоры
        entities:
          - binary_sensor.mosquitto
          - binary_sensor.rosiks_heater
          - binary_sensor.water_leak_sensor_158d00023a7ccf
      - type: entities
        title: Все трекеры
        entities:
          - device_tracker.iphone6
          - device_tracker.iphone6_bt
          - device_tracker.nexus_6p_bt
      - type: entities
        title: Климат
        entities:
          - climate.home_gas_heater
          - climate.rosik_ceramik_heater
      - type: entities
        title: Все группы
        entities:
          - group.climate_all
          - group.all_automations
          - group.all_devices
          - group.all_lights
          - group.all_scripts
          - group.all_switches
          - group.all_vacuum_cleaners
          - group.bedroom
          - group.darksky
          - group.migateway
          - group.people
          - group.pi
          - group.rosik
          - group.stats
          - group.system
          - group.water
      - type: entities
        title: Все логические переменные
        entities:
          - input_number.bedroomtimer
          - input_number.house_temp
          - input_number.rosikroomtimer
      - type: entities
        title: Весь свет
        entities:
          - light.gateway_light_7c49eb1a6912
      - type: entities
        title: Скрипты 
        entities:
          - script.sleep_timer
      - type: entities
        title: Все сенсоры
        entities:
          - sensor.dark_sky_cloud_coverage
          - sensor.dark_sky_humidity
          - sensor.dark_sky_precip
          - sensor.dark_sky_precip_intensity
          - sensor.dark_sky_pressure
          - sensor.dark_sky_summary
          - sensor.dark_sky_temperature
          - sensor.dark_sky_uv_index
          - sensor.dark_sky_wind_speed
          - sensor.disk_free_
          - sensor.heater_on
          - sensor.humidity_158d00023cf7f5
          - sensor.humidity_158d00024781ee
          - sensor.illumination_7c49eb1a6912
          - sensor.last_boot
          - sensor.memory_free
          - sensor.pi_cpu_temp
          - sensor.pressure_158d00023cf7f5
          - sensor.pressure_158d00024781ee
          - sensor.processor_use
          - sensor.ssl_cert_expiry
          - sensor.temperature_158d00023cf7f5
          - sensor.temperature_158d00024781ee
          - sensor.time_online
          - sensor.vacuum_battery
          - sensor.vacuum_cleaner_battery_level
          - sensor.vacuum_cleaner_cleaned_area
          - sensor.vacuum_cleaner_cleaning_time
          - sensor.vacuum_cleaner_error_sensor
          - sensor.vacuum_cleaner_filter_left
          - sensor.vacuum_cleaner_main_brush_left
          - sensor.vacuum_cleaner_side_brush_left
          - sensor.vacuum_cleaner_status
          - sensor.vacuum_cleaner_status_sensor
          - sensor.vacuum_status
          - sensor.water_pump_on
          - sun.sun
      - type: entities
        title: Пылесос
        entities:
          - sensor.vacuum_cleaner_error_sensor
          - sensor.vacuum_cleaner_status_sensor
          - sensor.vacuum_cleaner_battery_level
          - sensor.vacuum_cleaner_cleaned_area
          - sensor.vacuum_cleaner_status
          - sensor.vacuum_cleaner_cleaning_time
          - sensor.vacuum_cleaner_main_brush_left
          - sensor.vacuum_cleaner_side_brush_left
          - sensor.vacuum_cleaner_filter_left
      - type: entities
        title: Все переключатели
        entities:
          - switch.gas_boiler
          - switch.heater1
          - switch.sonoff
          - switch.waterpump
      - type: entities
        title: Все пылесосы
        entities:
          - vacuum.xiaomi_vacuum_cleaner
      - type: entities
        title: Все зоны
        entities:
          - zone.home
          - zone.ol4uk_work
      - type: entities
        title: Все автоматизации
        view: yes
        show_header_toggle: true
        entities:
          - automation.morning_off
          - automation.morning_on
          - automation.water_at_home
          - automation.water_leave_home
          - automation.climate_at_home 
          - automation.climate_leave_home
#################     
  # - icon: mdi:flash-auto
  #   title: Автоматизации
  #   background: radial-gradient(crimson, skyblue)
  #   cards:
      # - type: entities
      #   title: Пылесос
      #   view: yes
      #   show_header_toggle: true
      #   entities:
      #     - automation.exit_button_vacuum_on_childsleep_off
      #     - automation.exit_button_vacuum_on_childsleep_on
      #     - automation.vacuum_off
      #     - automation.vacuum_on
      #     - automation.vacuum_cleaner_error
      #     - automation.vacuum_cleaner_error_solved
