sensor:
  - platform: history_stats
    name: Kid's Heater ON last month
    entity_id: switch.heater1
    state: 'on'
    type: time
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
        days: 30
