- platform: history_stats
  name: water pump ON
  entity_id: switch.waterpump
  state: 'on'
  type: time
  start: '{{ 0 }}'
  end: '{{ now() }}'

- platform: history_stats
  name: heater ON
  entity_id: switch.heater1
  state: 'on'
  type: time
  start: '{{ 0 }}'
  end: '{{ now() }}'


  # start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  # end: '{{ now() }}'