- platform: mold_indicator
  name: mold 1st floor
  indoor_temp_sensor: sensor.temperature_158d00023cf7f5
  indoor_humidity_sensor: sensor.Humidity_158d00023cf7f5
  outdoor_temp_sensor: sensor.dark_sky_temperature
  calibration_factor: 1.135

- platform: mold_indicator
  name: mold 2nd floor
  indoor_temp_sensor: sensor.temperature_158d00024781ee
  indoor_humidity_sensor: sensor.humidity_158d00024781ee
  outdoor_temp_sensor: sensor.dark_sky_temperature
  calibration_factor: 1.135
