- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /
    - type: memory_free
    - type: processor_use
    - type: last_boot

# - platform: fastdotcom
#   minute:
#   - 0
#   - 30

- platform: speedtest
  minute: 30
  hour: 
    - 0
    - 6
    - 12 
    - 18
  monitored_conditions:
  - ping
  - download
  - upload