- platform: systemmonitor
  scan_interval: 60
  resources:
    - type: disk_free
      arg: /
    - type: memory_free
    - type: processor_use
    - type: last_boot

- platform: command_line
  name: PI CPU Temp
  scan_interval: 60
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) }}'

- platform: uptime
  name: Time Online
  scan_interval: 120
  unit_of_measurement: hours

# - platform: fastdotcom
#   minute:
#   - 0
#   - 30

# - platform: speedtest
#   minute: 30
#   hour: 
#     - 0
#     - 6
#     - 12 
#     - 18
#   monitored_conditions:
#   - ping
#   - download
#   - upload
#   