- platform: command_line
  name: SSL cert expiry
  unit_of_measurement: days
  scan_interval: 43200
  command: "ssl-cert-check -b -c /etc/letsencrypt/live/lezsmarthome.duckdns.org/cert.pem | awk '{ print $NF }'"
