- platform: template
  sensors:
    vacuum_cleaner_error_sensor:
      friendly_name: Vacuum Cleaner Error Sensor
      value_template: >-
        {% if states.vacuum.xiaomi_vacuum_cleaner.attributes.error is defined %}
          {{states.vacuum.xiaomi_vacuum_cleaner.attributes.error}}
        {% else %}
          No Error
        {% endif %}

- platform: template
  sensors:
    vacuum_cleaner_status_sensor:
      friendly_name: Vacuum Cleaner Status Sensor
      value_template: >-
        {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}


- platform: template
  sensors:
    vacuum_cleaner_battery_level:
      value_template: >
        {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_level }}
      friendly_name: Battery Level
      unit_of_measurement: '%'


    vacuum_cleaner_cleaned_area:
      value_template: >
        {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaned_area }}
      friendly_name: Cleaned Area
      unit_of_measurement: 'm²'


    vacuum_cleaner_status:
      value_template: >
        {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}
      friendly_name: Status


    vacuum_cleaner_cleaning_time:
      value_template: >
        {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaning_time }}
      friendly_name: Cleaning Time
      unit_of_measurement: 'min'


    vacuum_cleaner_main_brush_left:
      value_template: >
        {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.main_brush_left }}
      friendly_name: Main Brush Left
      unit_of_measurement: 'Hrs'


    vacuum_cleaner_side_brush_left:
      value_template: >
        {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.side_brush_left }}
      friendly_name: Side Brush Left
      unit_of_measurement: 'Hrs'


    vacuum_cleaner_filter_left:
      value_template: >
        {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.filter_left }}
      friendly_name: Filter Left
      unit_of_measurement: 'Hrs'

- platform: template
  sensors:
    vacuum_status:
      friendly_name: "Vacuum - Status"
      value_template: "Status: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}"


- platform: template
  sensors:
    vacuum_battery:
      friendly_name: "Vacuum - Battery"
      value_template: "Battery: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_level }}"
      device_class: battery
      unit_of_measurement: '%'