- alias: Heater Auto On for 60 Minutes Every 2 Hour From 11pm to 7am
  # id: FT Bed Heater Auto On for 30 Minutes Every 2 Hour From 11pm to 6am
  trigger: 
    platform: time
    minutes: '/120'
    seconds: 0
  condition:
  - condition: time
    after: '21:00:00'
    before: '07:00:00'
  action:
  - entity_id: switch.heater1
    service: switch.turn_on
  - delay: '00:60:00'
  # - delay: '00:{{ states.input_number.rosikroomtimer.state | int }}:00'
  - entity_id: switch.heater1
    service: switch.turn_off

  