- alias: water leave home
  trigger:
    platform: state
    # entity_id: device_tracker.iphone6
    entity_id: group.people
    to: not_home
  action:
  - service: switch.turn_off
    entity_id: switch.waterpump

- alias: water at home
  trigger:
    platform: state
    # entity_id: device_tracker.iphone6
    entity_id: group.people
    to: home
  action:
  - service: switch.turn_on
    entity_id: switch.waterpump
