- alias: water leave home
  trigger:
    platform: state
    # entity_id: device_tracker.iphone6
    entity_id: group.people
    to: not_home
  action:
  - service: switch.turn_off
    entity_id: switch.waterpump
  - service: telegram_bot.send_message
    data:
      title: 'water pump'
      message: 'is off'

- alias: water at home
  trigger:
    platform: state
    # entity_id: device_tracker.iphone6
    entity_id: group.people
    to: home
  action:
  - service: switch.turn_on
    entity_id: switch.waterpump
  - service: telegram_bot.send_message
    data:
      title: 'water pump'
      message: 'is on' 

- alias: water leak
  trigger:
    platform: state
    entity_id: binary_sensor.water_leak_sensor_158d00023a7ccf 
    to: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.waterpump
  - service: telegram_bot.send_message
    data:
      title: 'Alarm!'
      message: 'Water leak detected! water pump is off' 
